# Generated by Django 4.2.7 on 2026-06-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '10001_seed_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
