# Generated by Django 4.2.7 on 2026-05-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='fund_type',
            field=models.CharField(choices=[('general', 'General Fund'), ('building', 'Building Fund'), ('mission', 'Mission Fund'), ('benevolence', 'Benevolence Fund'), ('youth', 'Youth Fund'), ('worship', 'Worship Fund'), ('education', 'Education Fund'), ('emergency', 'Emergency Fund'), ('other', 'Other')], default='general', max_length=20),
        ),
    ]
