# Generated by Django 4.2.7 on 2026-06-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expensecategory_fundtype_donation_receipt_and_more'),
        ('finance', '9001_seed_fund_expense_types'),
    ]

    operations = [
    ]
