# Generated by Django 4.2.7 on 2026-05-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_family_portal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
