# Generated by Django 4.2.7 on 2026-05-25 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_family_family_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('certificate', 'Membership Certificate'), ('baptism', 'Baptism Certificate'), ('photo', 'Photo / ID'), ('transfer', 'Transfer Letter'), ('other', 'Other Document')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='member_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.member')),
            ],
            options={
                'db_table': 'member_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
