# Generated by Django 4.2.7 on 2026-06-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_memberdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ministry_groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='members.ministry'),
        ),
    ]
