# Generated by Django 4.2.7 on 2026-06-18 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0005_alter_member_ministry_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='portal_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_portal', to=settings.AUTH_USER_MODEL),
        ),
    ]
