# Generated by Django 4.2.7 on 2026-06-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_portal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='email',
        ),
        migrations.RemoveField(
            model_name='family',
            name='portal_user',
        ),
    ]
